env:
  TERM: xterm-256color

window:
  opacity: 0.95
  dynamic_title: true
  decorations: full
  startup_mode: Windowed
  dimensions:
    columns: 140
    lines: 38

scrolling:
  history: 50000

dpi:
  x: 128.0
  y: 128.0

draw_bold_text_with_bright_colors: true

font:
  normal:
    family: Fira Code
    style: Regular
  bold:
    family: Fira Code
    style: Bold

cursor:
  style:
    shape: Block
    blinking: Off
    thickness: 0.15

shell:
  program: /bin/zsh
  args:
    - --login

working_directory: ~

# Colors (Rosé Pine Theme)
colors:
  primary:
    background: '0x191724'
    foreground: '0xe0def4'
  cursor:
    text: '0xe0def4'
    cursor: '0x524f67'
  vi_mode_cursor:
    text: '0xe0def4'
    cursor: '0x524f67'
  line_indicator:
    foreground: None
    background: None
  selection:
    text: '0xe0def4'
    background: '0x403d52'
  normal:
    black: '0x26233a'
    red: '0xeb6f92'
    green: '0x31748f'
    yellow: '0xf6c177'
    blue: '0x9ccfd8'
    magenta: '0xc4a7e7'
    cyan: '0xebbcba'
    white: '0xe0def4'
  bright:
    black: '0x6e6a86'
    red: '0xeb6f92'
    green: '0x31748f'
    yellow: '0xf6c177'
    blue: '0x9ccfd8'
    magenta: '0xc4a7e7'
    cyan: '0xebbcba'
    white: '0xe0def4'
  hints:
    start:
      foreground: '#908caa'
      background: '#1f1d2e'
    end:
      foreground: '#6e6a86'
      background: '#1f1d2e'

key_bindings:
  - { key: K, mods: Command, mode: ~Vi|~Search, chars: "\x0c" }
  - { key: K, mods: Command, mode: ~Vi|~Search, action: ClearHistory }
  - { key: Key0, mods: Command, action: ResetFontSize }
  - { key: Equals, mods: Command, action: IncreaseFontSize }
  - { key: Plus, mods: Command, action: IncreaseFontSize }
  - { key: NumpadAdd, mods: Command, action: IncreaseFontSize }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Command, action: DecreaseFontSize }
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: C, mods: Command, mode: Vi|~Search, action: ClearSelection }
  - { key: H, mods: Command, action: Hide }
  - { key: H, mods: Command|Alt, action: HideOtherApplications }
  - { key: M, mods: Command, action: Minimize }
  - { key: Q, mods: Command, action: Quit }
  - { key: W, mods: Command, action: Quit }
  - { key: N, mods: Command, action: SpawnNewInstance }
  - { key: F, mods: Command|Control, action: ToggleFullscreen }
  - { key: F, mods: Command, mode: ~Search, action: SearchForward }
  - { key: B, mods: Command, mode: ~Search, action: SearchBackward }
