env:
  TERM: xterm-256color

window:
  opacity: 0.95
  dynamic_title: true
  padding:
    x: 10
    y: 10
  decorations: full
  startup_mode: Windowed
  dimensions:
    columns: 140
    lines: 38

scrolling:
  history: 50000

dpi:
  x: 128.0
  y: 128.0

draw_bold_text_with_bright_colors: true

font:
  normal:
    family: FiraCode Nerd Font Mono
    style: Regular
  bold:
    family: FiraCode Nerd Font Mono
    style: Bold

cursor:
  style:
    shape: Block
    blinking: Off
    thickness: 0.15

shell:
  program: /bin/zsh
  args:
    - --login

working_directory: ~

# Colors (Aura Theme)
colors:
  primary:
    background: '#15141b'
    foreground: '#edecee'
  cursor:
    cursor: '#a277ff'
  normal:
    black: '#110f18'
    red: '#ff6767'
    green: '#61ffca'
    yellow: '#ffca85'
    blue: '#a277ff'
    magenta: '#a277ff'
    cyan: '#61ffca'
    white: '#edecee'
  bright:
    black: '#4d4d4d'
    red: '#ff6767'
    green: '#61ffca'
    yellow: '#ffca85'
    blue: '#a277ff'
    magenta: '#a277ff'
    cyan: '#61ffca'
    white: '#edecee'

key_bindings:
  - { key: K, mods: Command, mode: ~Vi|~Search, chars: "\x0c" }
  - { key: K, mods: Command, mode: ~Vi|~Search, action: ClearHistory }
  - { key: Key0, mods: Command, action: ResetFontSize }
  - { key: Equals, mods: Command, action: IncreaseFontSize }
  - { key: Plus, mods: Command, action: IncreaseFontSize }
  - { key: NumpadAdd, mods: Command, action: IncreaseFontSize }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Command, action: DecreaseFontSize }
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: C, mods: Command, mode: Vi|~Search, action: ClearSelection }
  - { key: H, mods: Command, action: Hide }
  - { key: H, mods: Command|Alt, action: HideOtherApplications }
  - { key: M, mods: Command, action: Minimize }
  - { key: Q, mods: Command, action: Quit }
  - { key: W, mods: Command, action: Quit }
  - { key: N, mods: Command, action: SpawnNewInstance }
  - { key: F, mods: Command|Control, action: ToggleFullscreen }
  - { key: F, mods: Command, mode: ~Search, action: SearchForward }
  - { key: B, mods: Command, mode: ~Search, action: SearchBackward }
